apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
    container: 
      - name: kubectl
        image: joshendriks/alpinr-k8s
        command:
          - /bin/cat
        tty: true
      - name: kaniko
        image: gcr.io/kaniko-project/executor:debug
        command:
          - /busybox/cat
        tty: true
        volumeMounts:
          - name: kaniko-secret
            mountPath: /kanico/.docker
    volumes:
      - name: kaniko-secret
        secret:
          secretName: regcred
          items:
            - key: .dockerconfigjson
              path: config.json